name: Daily Commit

on:
  schedule:
    - cron: '0 6 * * *'   # 6 AM UTC (11:30 AM IST)
    - cron: '57 6 * * *'  # 06:57 AM UTC = 12:27 PM IST
    - cron: '0 18 * * *'  # 6 PM UTC (11:30 PM IST)
  workflow_dispatch:      # Manual trigger

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Make a dummy commit
        run: |
          date >> daily.txt
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add activity.txt
          git commit -m "🕒 Daily commit - $(date -u '+%Y-%m-%d %H:%M:%S')"
          git push
